#!/bin/bash
source /opt/dirac/bashrc
RUNSVCTRL=`which runsvctrl`
$RUNSVCTRL d /opt/dirac/startup/*
killall runsv svlogd
killall runsvdir
# If you did also installed a MySQL server uncomment the next line
dirac-stop-mysql

